// arrays of supported adapters

/*
Default Template:
	adapterID: { 			// ID for adapter, it should be the same name as in settings etc.
		adapterKey:         // same like io-package adapter list tableDevices.adapterKey
		selektor: '',		// main datapoint of one device. Should be available for all devices. So the adapter can found all devices
		timeSelector: '',	// from which datapoint should the time be taken for the last contact
		adapterID: '',		// same id as above
		adapter: '',		// Adapter Name for notifications and tables
		rssiState: 'none',	// rssi or percent datapoint of link quality (optional)
		battery: 'none',	// battery datapoint (optional)
		reach: 'none',		// reachable or connected datapoint (optional)
		isLowBat: 'none',	// lowBat datapoint (optional)
		id: 'none',			// datapoint with name of device (optional)
		upgrade: 'none',	// update datapoint that indicates available updates for the device (optional)
	},


	standard vorlage für neue adapter

	adapterID: {
	    adapterKey: '',
		selektor: '',
		timeSelector: '',
		adapterID: '',
		adapter: '',
		rssiState: 'none',
		battery: 'none',
		charger: 'none',
		reach: 'none',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},

    sonderlocke

    hmrpc
    shelly

	in io-package muss der adapter auch rein sonst keine Auswahl im admin

*/

const adapterArray = {
	alexa2: {
		adapterKey: 'alexa2Devices',
		selektor: 'alexa2.*.online',
		timeSelector: '.online',
		adapterID: 'alexa2',
		adapter: 'Alexa2',
		battery: 'none',
		reach: '.online',
		isLowBat: 'none',
	},
	apcups: {
		adapterKey: 'apcupsDevices',
		selektor: 'apcups.*.status',
		timeSelector: '.status',
		adapterID: 'apcups',
		adapter: 'Apc UPS',
		battery: '.batteryCharge',
		reach: '.info.connection',
		isLowBat: 'none',
		id: '.model',
	},
	ble: {
		adapterKey: 'bleDevices',
		selektor: 'ble.*.rssi',
		timeSelector: '.rssi',
		adapterID: 'ble',
		adapter: 'Ble',
		battery: '.battery',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
	},
	deconz: {
		adapterKey: 'deconzDevices',
		selektor: 'deconz.*.reachable',
		timeSelector: '.reachable',
		adapterID: 'deconz',
		adapter: 'Deconz',
		battery: '.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	ecovacsdeebot: {
		adapterKey: 'ecovacsdeebotDevices',
		selektor: 'ecovacs-deebot.*.connection',
		timeSelector: '.connectionUptime',
		adapterID: 'ecovacsdeebot',
		adapter: 'Ecovacs-Deebot',
		rssiState: '.network.wifiSignal',
		battery: '.battery',
		reach: '.connection',
		isLowBat: 'none',
		id: '.deviceName',
		upgrade: 'none',
	},
	enocean: {
		adapterKey: 'enoceanDevices',
		selektor: 'enocean.*.rssi',
		timeSelector: '.rssi',
		adapterID: 'enocean',
		adapter: 'Enocean',
		battery: '.BS',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
	},
	esphome: {
		adapterKey: 'esphomeDevices',
		selektor: 'esphome.*._online',
		timeSelector: '._online',
		adapterID: 'esphome',
		adapter: 'ESPHome',
		battery: 'none',
		reach: '._online',
		isLowBat: 'none',
		id: '.name',
	},
	eusec: {
		adapterKey: 'eusecDevices',
		selektor: 'eusec.*.software_version',
		timeSelector: '.software_version',
		adapterID: 'eusec',
		adapter: 'euSec',
		battery: '.battery',
		rssiState: '.wifi_rssi',
		reach: '.connection',
		isLowBat: '.battery_low',
		id: '.name',
	},
	fhemTFAsensors: {
		adapterKey: 'fhemTFAsensorsDevices',
		selektor: 'fhem.*.batteryState',
		timeSelector: '.state',
		adapterID: 'fhemTFAsensors',
		adapter: 'FHEM',
		rssiState: 'none',
		battery: 'none',
		reach: 'none',
		isLowBat: '.batteryState',
		id: 'none',
		upgrade: 'none',
	},
	freeair: {
		adapterKey: 'freeairDevices',
		selektor: 'freeair.*.isOnline',
		timeSelector: '.isOnline',
		adapterID: 'freeair',
		adapter: 'FreeAir 100',
		rssiState: '.rssi',
		battery: 'none',
		reach: '.isOnline',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	fritzdect: {
		adapterKey: 'fritzdectDevices',
		selektor: 'fritzdect.*.present',
		timeSelector: '.present',
		adapterID: 'fritzdect',
		adapter: 'Fritz Dect',
		battery: '.battery',
		reach: '.present',
		isLowBat: 'none',
	},
	fullybrowser: {
		adapterKey: 'fullybrowserDevices',
		selektor: 'fullybrowser.*.isFullyAlive',
		timeSelector: '.isFullyAlive',
		adapterID: 'fullybrowser',
		adapter: 'fullyBrowser',
		rssiState: '.Info.wifiSignalLevel',
		battery: '.Info.batteryLevel',
		reach: '.isFullyAlive',
		isLowBat: 'none',
		id: '.Info.hostname4',
		id2: '.Info.deviceModel',
	},
	fullybrowserV3: {
		adapterKey: 'fullybrowserV3Devices',
		selektor: 'fullybrowser.*.alive',
		timeSelector: '.alive',
		adapterID: 'fullybrowserV3',
		adapter: 'fullyBrowser',
		rssiState: '.Info.wifiSignalLevel',
		battery: '.Info.batteryLevel',
		reach: '.alive',
		isLowBat: 'none',
		id: 'none',
	},
	fullyMQTT: {
		adapterKey: 'fullyMQTTDevices',
		selektor: 'fully-mqtt.*.alive',
		timeSelector: '.alive',
		adapterID: 'fullyMQTT',
		adapter: 'Fully-MQTT',
		rssiState: 'none',
		battery: '.Info.batteryLevel',
		reach: '.alive',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	harmony: {
		adapterKey: 'harmonyDevices',
		selektor: 'harmony.*.hubConnected',
		timeSelector: '.activities.currentStatus',
		adapterID: 'harmony',
		adapter: 'Harmony',
		battery: 'none',
		reach: '.hubConnected',
		isLowBat: 'none',
	},
	ham: {
		adapterKey: 'hamDevices',
		selektor: 'ham.*.Battery-Level',
		timeSelector: '.Battery-Level',
		adapterID: 'ham',
		adapter: 'Ham',
		battery: '.Battery-Level',
		reach: 'none',
		isLowBat: 'none',
		id: '.Name',
	},
	hmiP: {
		adapterKey: 'hmiPDevices',
		selektor: 'hmip.*.rssiDeviceValue',
		timeSelector: '.rssiDeviceValue',
		adapterID: 'hmiP',
		adapter: 'Homematic IP',
		rssiState: '.rssiDeviceValue',
		battery: 'none',
		reach: '.unreach',
		isLowBat: '.lowBat',
		upgrade: '.info.updateState',
	},
	hmrpc: {
		adapterKey: 'hmrpcDevices',
		selektor: 'hm-rpc.*.RSSI_PEER',
		timeSelector: '.UNREACH',
		adapterID: 'hmrpc',
		adapter: 'Homematic RPC',
		rssiState: '.RSSI_DEVICE',
		rssiPeerState: '.RSSI_PEER',
		battery: '.OPERATING_VOLTAGE',
		reach: '.UNREACH_ALARM',
		isLowBat: '.LOW_BAT_ALARM',
		isLowBat2: '.LOWBAT_ALARM',
		isLowBat3: '.LOW_BAT',
		stateValue: '.1.STATE',
		faultReporting: '.4.FAULT_REPORTING',
		hmDNBattery: '.4.BATTERY_STATE',
		upgrade: '.UPDATE_PENDING_ALARM',
	},
	homeconnect: {
		adapterKey: 'homeconnectDevices',
		selektor: 'homeconnect.*.general.connected',
		timeSelector: '.connected',
		adapterID: 'homeconnect',
		adapter: 'Home Connect',
		rssiState: 'none',
		battery: 'none',
		reach: '.connected',
		isLowBat: 'none',
		id: '.name',
		upgrade: 'none',
	},
	homee: {
		// battery only structure problem
		adapterKey: 'homeeDevices',
		selektor: 'homee.*.BatteryLevel*',
		timeSelector: '.connected',
		adapterID: 'homee',
		adapter: 'Homee',
		rssiState: 'none',
		battery: '.BatteryLevel*',
		reach: 'none',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	homekitController: {
		adapterKey: 'homekitControllerDevices',
		selektor: 'homekit-controller.*.connected',
		timeSelector: '.lastDiscovered',
		adapterID: 'homekitController',
		adapter: 'Homekit Controller',
		rssiState: 'none',
		battery: 'none',
		reach: '.connected',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	hs100: {
		adapterKey: 'hs100Devices',
		selektor: 'hs100.*.last_update',
		timeSelector: '.last_update',
		adapterID: 'hs100',
		adapter: 'hs100',
		battery: 'none',
		reach: 'none',
		isLowBat: 'none',
	},
	hue: {
		adapterKey: 'hueDevices',
		selektor: 'hue.*.reachable',
		timeSelector: '.reachable',
		adapterID: 'hue',
		adapter: 'Philips Hue',
		battery: '.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	hueExt: {
		adapterKey: 'hueExtDevices',
		selektor: 'hue-extended.*.reachable',
		timeSelector: '.reachable',
		adapterID: 'hueExt',
		adapter: 'Philips Hue Extended',
		battery: '.config.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	innogy: {
		adapterKey: 'innogyDevices',
		selektor: 'innogy-smarthome.*.IsReachable',
		timeSelector: '.IsReachable',
		adapterID: 'innogy',
		adapter: 'Innogy Smarthome',
		battery: 'none',
		rssiState: 'none',
		reach: '.IsReachable',
		isLowBat: '.LowBattery',
	},
	jeelink: {
		adapterKey: 'jeelinkDevices',
		selektor: 'jeelink.*.lowBatt',
		timeSelector: '.lowBatt',
		adapterID: 'jeelink',
		adapter: 'Jeelink',
		battery: 'none',
		reach: 'none',
		isLowBat: '.lowBatt',
	},
	loqedSmartLock: {
		adapterKey: 'loqedSmartLockDevices',
		selektor: 'loqed.*.connection',
		timeSelector: '.lockStatus.batteryPercentage',
		adapterID: 'loqedSmartLock',
		adapter: 'Loqed Smart Lock',
		battery: '.lockStatus.batteryPercentage',
		rssiState: 'none',
		reach: '.connection',
		isLowBat: '.lowBatt',
	},
	lupusec: {
		adapterKey: 'lupusecDevices',
		selektor: 'lupusec.*.cond_ok',
		timeSelector: '.cond_ok',
		adapterID: 'lupusec',
		adapter: 'Lupusec',
		battery: 'none',
		rssiState: '.rssi',
		reach: '.cond_ok',
		isLowBat: '.battery_ok',
		id: 'none',
	},
	matter: {
		adapterKey: 'matterDevices',
		selektor: 'matter.*.online',
		adapterID: 'matter',
		adapter: 'matter',
		rssiState: 'none',
		battery: '.BATTERY',
		reach: '.connection',
		isLowBat: '.LOWBAT',
		id: 'none',
		upgrade: 'none',
	},
	maxcube: {
		adapterKey: 'maxcubeDevices',
		selektor: 'maxcube.*.link_error',
		timeSelector: '.link_error',
		adapterID: 'maxcube',
		adapter: 'Max! Cube',
		battery: 'none',
		reach: '.error',
		isLowBat: '.battery_low',
	},
	meross: {
		adapterKey: 'merossDevices',
		selektor: 'meross.*.online',
		timeSelector: '.online',
		adapterID: 'meross',
		adapter: 'Meross',
		battery: '.battery',
		reach: '.online',
		isLowBat: 'none',
	},
	mihome: {
		adapterKey: 'mihomeDevices',
		selektor: 'mihome.*.percent',
		timeSelector: '.percent',
		adapterID: 'mihome',
		adapter: 'MiHome',
		battery: '.percent',
		reach: 'none',
		isLowBat: 'none',
	},
	mihomeGW: {
		adapterKey: 'mihomeGWDevices',
		selektor: 'mihome.*.connected',
		timeSelector: '.connected',
		adapterID: 'mihome',
		adapter: 'MiHome',
		battery: 'none',
		reach: '.connected',
		isLowBat: 'none',
	},
	mihomeVacuum: {
		adapterKey: 'mihomeVacuumDevices',
		selektor: 'mihome-vacuum.*.connection',
		timeSelector: '.connection',
		adapterID: 'mihomeVacuum',
		adapter: 'MiHome Vacuum',
		rssiState: '.deviceInfo.wifi_signal',
		battery: '.info.battery',
		battery2: '.control.battary_life',
		reach: '.info.connection',
		isLowBat: 'none',
		id: '.deviceInfo.model',
	},
	mqttClientZigbee2Mqtt: {
		adapterKey: 'mqttClientZigbee2MqttDevices',
		selektor: 'mqtt-client.*.zigbee2mqtt.*.availability',
		timeSelector: '.availability',
		adapterID: 'mqttClientZigbee2Mqtt',
		adapter: 'MQTT-Client',
		battery: '.battery',
		rssiState: '.link_quality',
		reach: '.availability',
		isLowBat: '.battery_low',
	},
	mqttNuki: {
		adapterKey: 'mqttNukiDevices',
		selektor: 'mqtt.*.lock.state',
		timeSelector: '.rssi',
		adapterID: 'mqttNuki',
		adapter: 'MQTT',
		battery: '.battery.level',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
	},
	musiccast: {
		adapterKey: 'musiccastDevices',
		selektor: 'musiccast.*.online',
		timeSelector: '.online',
		adapterID: 'musiccast',
		adapter: 'MusicCast',
		battery: 'none',
		rssiState: 'none',
		reach: '.online',
		isLowBat: 'none',
	},
	netatmo: {
		adapterKey: 'netatmoDevices',
		selektor: 'netatmo.*.LastUpdate',
		timeSelector: '.LastUpdate',
		adapterID: 'netatmo',
		adapter: 'Netatmo',
		rssiState: '.WifiStatus',
		rfState: '.RfStatus',
		battery: '.BatteryStatus',
		reach: 'none',
		isLowBat: 'none',
	},
	nukiExt: {
		adapterKey: 'nukiExtDevices',
		selektor: 'nuki-extended.*.lastDataUpdate',
		timeSelector: '.lastDataUpdate',
		adapterID: 'nukiExt',
		adapter: 'Nuki Extended',
		rssiState: 'none',
		battery: '.batteryChargeState',
		reach: 'none',
		isLowBat: '.batteryCritical',
	},
	nut: {
		adapterKey: 'nutDevices',
		selektor: 'nut.*.charge',
		timeSelector: '.charge',
		adapterID: 'nut',
		adapter: 'Nut',
		battery: '.charge',
		reach: 'none',
		isLowBat: 'none',
	},
	ping: {
		adapterKey: 'pingDevices',
		selektor: 'ping.*.alive',
		timeSelector: '.alive',
		adapterID: 'ping',
		adapter: 'Ping',
		battery: 'none',
		reach: '.alive',
		isLowBat: 'none',
	},
	proxmox: {
		adapterKey: 'proxmoxDevices',
		selektor: 'proxmox.*.status',
		timeSelector: '.uptime',
		adapterID: 'proxmox',
		adapter: 'Proxmox',
		battery: 'none',
		reach: '.status',
		isLowBat: 'none',
		rssiState: 'none',
	},
	ring: {
		adapterKey: 'ringDevices',
		selektor: 'ring.*.latest_signal_strength',
		timeSelector: '.latest_signal_strength',
		adapterID: 'ring',
		adapter: 'Ring',
		rssiState: '.latest_signal_strength',
		battery: '.battery_percentage',
		charger: '.external_connection',
		reach: 'none',
		isLowBat: 'none',
		id: 'none',
		upgrade: '.firmware',
	},
	roomba: {
		adapterKey: 'roombaDevices',
		selektor: 'roomba.*.signal',
		timeSelector: '.signal',
		adapterID: 'roomba',
		adapter: 'Roomba',
		battery: '.battery',
		reach: '._connected',
		rssiState: '.signal',
		isLowBat: 'none',
		id: '.device.name',
	},
	shelly: {
		adapterKey: 'shellyDevices',
		selektor: 'shelly.*.uptime',
		timeSelector: '.uptime',
		adapterID: 'shelly',
		adapter: 'Shelly',
		rssiState: '.rssi',
		battery: '.sensor.battery',
		battery2: '.bat.value',
		battery3: '.DevicePower0.BatteryPercent',
		charger: '.bat.charger',
		reach: '.online',
		isLowBat: 'none',
		upgrade: '.firmware',
	},
	smartgarden: {
		adapterKey: 'smartgardenDevices',
		selektor: 'smartgarden.*.serial_value',
		timeSelector: '.rfLinkLevel_timestamp',
		adapterID: 'smartgarden',
		adapter: 'Smartgarden',
		rssiState: '.rfLinkLevel_value',
		battery: '.batteryLevel_value',
		reach: '.rfLinkState_value',
		isLowBat: 'none',
		id: '.name_value',
		upgrade: 'none',
	},
	sonoff: {
		adapterKey: 'sonoffDevices',
		selektor: 'sonoff.*.alive',
		timeSelector: '.Uptime',
		adapterID: 'sonoff',
		adapter: 'Sonoff',
		rssiState: '.Wifi_RSSI',
		battery: '.battery',
		reach: '.alive',
		uptime: '.Uptime',
		isLowBat: 'none',
		id: '.DeviceName',
	},
	sonos: {
		adapterKey: 'sonosDevices',
		selektor: 'sonos.*.alive',
		timeSelector: '.alive',
		adapterID: 'sonos',
		adapter: 'Sonos',
		battery: 'none',
		reach: '.alive',
		isLowBat: 'none',
	},
	sureflap: {
		adapterKey: 'sureflapDevices',
		selektor: 'sureflap.*.online',
		timeSelector: '.online',
		adapterID: 'sureflap',
		adapter: 'Sure Flap',
		battery: '.battery_percentage',
		reach: '.online',
		isLowBat: 'none',
	},
	switchbotBle: {
		adapterKey: 'switchbotBleDevices',
		selektor: 'switchbot-ble.*.rssi',
		timeSelector: '.rssi',
		adapterID: 'switchbotBle',
		adapter: 'Switchbot Ble',
		battery: '.battery',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
		id: '.id',
	},
	tado: {
		adapterKey: 'tadoDevices',
		selektor: 'tado.*.batteryState',
		timeSelector: '.batteryState',
		adapterID: 'tado',
		adapter: 'Tado',
		rssiState: 'none',
		battery: 'none',
		reach: '.connectionState.value',
		isLowBat: '.batteryState',
		id: 'none',
	},
	tapo: {
		adapterKey: 'tapoDevices',
		selektor: 'tapo.*.last_update',
		timeSelector: '.last_update',
		adapterID: 'tapo',
		adapter: 'Tapo',
		rssiState: '.rssi',
		battery: 'none',
		reach: 'none',
		isLowBat: 'none',
		id: 'none',
	},
	tradfri: {
		adapterKey: 'tradfriDevices',
		selektor: 'tradfri.*.lastSeen',
		timeSelector: '.lastSeen',
		adapterID: 'tradfri',
		adapter: 'Tradfri',
		rssiState: 'none',
		battery: '.batteryPercentage',
		reach: '.alive',
		isLowBat: 'none',
		id: 'none',
	},
	tuya: {
		adapterKey: 'tuyaDevices',
		selektor: 'tuya.*.online',
		timeSelector: '.online',
		adapterID: 'tuya',
		adapter: 'Tuya',
		rssiState: 'none',
		battery: 'none',
		reach: '.online',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	unifi: {
		adapterKey: 'unifiDevices',
		selektor: 'unifi.*.state',
		timeSelector: '.uptime',
		adapterID: 'unifi',
		adapter: 'Unifi',
		battery: 'none',
		reach: '.state',
		isLowBat: 'none',
		id: 'none',
		upgrade: '.upgradable',
	},
	'unifi-network': {
		adapterKey: 'unifi-networkDevices',
		selektor: 'unifi-network.*.devices.*.isOnline',
		timeSelector: '.uptime',
		adapterID: 'unifi-network',
		adapter: 'Unifi Network',
		battery: 'none',
		reach: '.isOnline',
		isLowBat: 'none',
		id: 'none',
		upgrade: '.upgradable',
	},
	viessmann: {
		adapterKey: 'viessmannDevices',
		selektor: 'viessmann.*.info.connection',
		timeSelector: '.lastPoll',
		adapterID: 'viessmann',
		adapter: 'Viessmann',
		rssiState: 'none',
		battery: 'none',
		reach: '.connection',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	wifilight: {
		adapterKey: 'wifilightDevices',
		selektor: 'wifilight.*.reachable',
		timeSelector: '.reachable',
		adapterID: 'wifilight',
		adapter: 'Wifilight',
		rssiState: 'none',
		battery: 'none',
		reach: '.reachable',
		isLowBat: 'none',
		id: 'none',
		upgrade: 'none',
	},
	wled: {
		adapterKey: 'wledDevices',
		selektor: 'wled.*._online',
		timeSelector: '._online',
		adapterID: 'wled',
		adapter: 'WLED',
		rssiState: '.wifi.rssi',
		battery: 'none',
		reach: '._online',
		isLowBat: 'none',
		id: '.name',
		upgrade: 'none',
	},
	xsense: {
		adapterKey: 'xsenseDevices',
		selektor: 'xsense.*.online',
		timeSelector: '.online',
		adapterID: 'xsense',
		adapter: 'XSense',
		rssiState: 'none',
		battery: '.batInfo',
		reach: '.online',
		isLowBat: '.batInfo',
		id: 'none',
		upgrade: 'none',
	},
	yeelight: {
		adapterKey: 'yeelightDevices',
		selektor: 'yeelight-2.*.connect',
		timeSelector: '.connect',
		adapterID: 'yeelight',
		adapter: 'Yeelight',
		battery: 'none',
		reach: '.connect',
		isLowBat: 'none',
	},
	zigbee: {
		adapterKey: 'zigbeeDevices',
		selektor: 'zigbee.*.link_quality',
		timeSelector: '.link_quality',
		adapterID: 'zigbee',
		adapter: 'Zigbee',
		battery: '.battery',
		battery2: '.battery_state',
		rssiState: '.link_quality',
		reach: '.available',
		isLowBat: '.battery_low',
	},
	zigbee2MQTT: {
		adapterKey: 'zigbee2mqttDevices',
		selektor: 'zigbee2mqtt.*.link_quality',
		timeSelector: '.link_quality',
		adapterID: 'zigbee2MQTT',
		adapter: 'Zigbee2MQTT',
		battery: '.battery',
		battery2: '.battery_state',
		rssiState: '.link_quality',
		reach: '.available',
		isLowBat: '.battery_low',
	},
	zwave2: {
		adapterKey: 'zwave2Devices',
		selektor: 'zwave2.*.ready',
		timeSelector: '.status',
		adapterID: 'zwave2',
		adapter: 'Z-wave 2',
		battery: '.Battery.level',
		reach: '.ready',
		rssiState: 'none',
		isLowBat: '.Battery.isLow',
	},
  zwavews: {
		adapterKey: 'zwavewsDevices',
		selektor: 'zwavews.*.ready',
		timeSelector: '.status',
		adapterID: 'zwavews',
		adapter: 'Zwavews',
		battery: '.Battery.level',
		reach: '.ready',
		rssiState: 'none',
		isLowBat: '.Battery.isLow',
	},
};

module.exports = adapterArray;
