// arrays of supported adapters
const arrApart = {
	alexa2: {
		Selektor: 'alexa2.*.online',
		adapterID: 'alexa2',
		adapter: 'Alexa2',
		battery: 'none',
		reach: '.online',
		isLowBat: 'none',
	},
	ble: {
		Selektor: 'ble.*.rssi',
		adapterID: 'ble',
		adapter: 'Ble',
		battery: '.battery',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
	},
	deconz: {
		Selektor: 'deconz.*.reachable',
		adapterID: 'deconz',
		adapter: 'Deconz',
		battery: '.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	enocean: {
		Selektor: 'enocean.*.rssi',
		adapterID: 'enocean',
		adapter: 'Enocean',
		battery: '.BS',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
	},
	esphome: {
		Selektor: 'esphome.*._online',
		adapterID: 'esphome',
		adapter: 'ESPHome',
		battery: 'none',
		reach: '._online',
		isLowBat: 'none',
		id: '.name',
	},
	fritzdect: {
		Selektor: 'fritzdect.*.present',
		adapterID: 'fritzdect',
		adapter: 'Fritz Dect',
		battery: '.battery',
		reach: '.present',
		isLowBat: '.batterylow',
	},
	harmony: {
		Selektor: 'harmony.*.hubConnected',
		adapterID: 'harmony',
		adapter: 'Harmony',
		battery: 'none',
		reach: '.hubConnected',
		isLowBat: 'none',
	},
	ham: {
		Selektor: 'ham.*.Battery-Level',
		adapterID: 'ham',
		adapter: 'Ham',
		battery: '.Battery-Level',
		reach: 'none',
		isLowBat: 'none',
		id: '.Name',
	},
	hmiP: {
		Selektor: 'hmip.*.rssiDeviceValue',
		adapterID: 'hmiP',
		adapter: 'Homematic IP',
		rssiState: '.rssiDeviceValue',
		battery: 'none',
		reach: '.unreach',
		isLowBat: '.lowBat',
	},
	hmrpc: {
		Selektor: '0_userdata.0.hm-rpc.*.UNREACH',
		adapterID: 'hmrpc',
		adapter: 'Homematic RPC',
		rssiState: '.RSSI_DEVICE',
		rssiPeerState: '.RSSI_PEER',
		battery: '.OPERATING_VOLTAGE',
		reach: '.UNREACH',
		isLowBat: '.LOW_BAT',
		isLowBat2: '.LOWBAT',
		stateValue: '.1.STATE',
	},
	hs100: {
		Selektor: 'hs100.*.last_update',
		adapterID: 'hs100',
		adapter: 'hs100',
		battery: 'none',
		reach: 'none',
		isLowBat: 'none',
	},
	hue: {
		Selektor: 'hue.*.reachable',
		adapterID: 'hue',
		adapter: 'Philips Hue',
		battery: '.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	hueExt: {
		Selektor: 'hue-extended.*.reachable',
		adapterID: 'hueExt',
		adapter: 'Philips Hue Extended',
		battery: '.config.battery',
		reach: '.reachable',
		isLowBat: 'none',
	},
	jeelink: {
		Selektor: 'jeelink.*.lowBatt',
		adapterID: 'jeelink',
		adapter: 'Jeelink',
		battery: 'none',
		reach: 'none',
		isLowBat: '.lowBatt',
	},
	lupusec: {
		Selektor: 'lupusec.*.cond_ok',
		adapterID: 'lupusec',
		adapter: 'Lupusec',
		battery: 'none',
		rssiState: '.rssi',
		reach: '.cond_ok',
		isLowBat: '.battery_ok',
		id: 'none',
	},
	maxcube: {
		Selektor: 'maxcube.*.link_error',
		adapterID: 'maxcube',
		adapter: 'Max! Cube',
		battery: 'none',
		reach: '.error',
		isLowBat: '.battery_low',
	},
	meross: {
		Selektor: 'meross.*.online',
		adapterID: 'meross',
		adapter: 'Meross',
		battery: '.battery',
		reach: '.online',
		isLowBat: 'none',
	},
	mihome: {
		Selektor: 'mihome.*.percent',
		adapterID: 'mihome',
		adapter: 'MiHome',
		battery: '.percent',
		reach: 'none',
		isLowBat: 'none',
	},
	mihomeGW: {
		Selektor: 'mihome.*.connected',
		adapterID: 'mihome',
		adapter: 'MiHome',
		battery: 'none',
		reach: '.connected',
		isLowBat: 'none',
	},
	mihomeVacuum: {
		Selektor: 'mihome-vacuum.*.connection',
		adapterID: 'mihomeVacuum',
		adapter: 'MiHome Vacuum',
		rssiState: '.deviceInfo.wifi_signal',
		battery: '.info.battery',
		battery2: '.control.battary_life',
		reach: '.info.connection',
		isLowBat: 'none',
		id: '.deviceInfo.model',
	},
	netatmo: {
		Selektor: 'netatmo.*.LastUpdate',
		adapterID: 'netatmo',
		adapter: 'Netatmo',
		rssiState: '.WifiStatus',
		rfState: '.RfStatus',
		battery: '.BatteryStatus',
		reach: 'none',
		isLowBat: 'none',
	},
	nukiExt: {
		Selektor: 'nuki-extended.*.lastDataUpdate',
		adapterID: 'nukiExt',
		adapter: 'Nuki Extended',
		rssiState: 'none',
		battery: '.batteryChargeState',
		reach: 'none',
		isLowBat: '.batteryCritical',
	},
	nut: {
		Selektor: 'nut.*.charge',
		adapterID: 'nut',
		adapter: 'Nut',
		battery: '.charge',
		reach: 'none',
		isLowBat: 'none',
	},
	ping: {
		Selektor: 'ping.*.alive',
		adapterID: 'ping',
		adapter: 'Ping',
		battery: 'none',
		reach: '.alive',
		isLowBat: 'none',
	},
	roomba: {
		Selektor: 'roomba.*.signal',
		adapterID: 'roomba',
		adapter: 'Roomba',
		battery: '.battery',
		reach: '._connected',
		rssiState: '.signal',
		isLowBat: 'none',
		id: '.device.name',
	},
	shelly: {
		Selektor: 'shelly.*.uptime',
		adapterID: 'shelly',
		adapter: 'Shelly',
		rssiState: '.rssi',
		battery: '.sensor.battery',
		reach: '.online',
		isLowBat: 'none',
	},
	sonoff: {
		Selektor: 'sonoff.*.alive',
		adapterID: 'sonoff',
		adapter: 'Sonoff',
		rssiState: '.Wifi_RSSI',
		battery: '.battery',
		reach: '.alive',
		uptime: '.Uptime',
		isLowBat: 'none',
	},
	sonos: {
		Selektor: '0_userdata.0.sonos.*.alive',
		adapterID: 'sonos',
		adapter: 'Sonos',
		battery: 'none',
		reach: '.alive',
		isLowBat: 'none',
	},
	switchbotBle: {
		Selektor: 'switchbot-ble.*.rssi',
		adapterID: 'switchbotBle',
		adapter: 'Switchbot Ble',
		battery: '.battery',
		rssiState: '.rssi',
		reach: 'none',
		isLowBat: 'none',
		id: '.id',
	},
	tado: {
		Selektor: 'tado.*.batteryState',
		adapterID: 'tado',
		adapter: 'Tado',
		rssiState: 'none',
		battery: 'none',
		reach: '.connectionState.value',
		isLowBat: '.batteryState',
		id: 'none',
	},
	tapo: {
		Selektor: 'tapo.*.last_update',
		adapterID: 'tapo',
		adapter: 'Tapo',
		rssiState: '.rssi',
		battery: 'none',
		reach: 'none',
		isLowBat: 'none',
		id: 'none',
	},
	tradfri: {
		Selektor: 'tradfri.*.lastSeen',
		adapterID: 'tradfri',
		adapter: 'Tradfri',
		rssiState: 'none',
		battery: '.batteryPercentage',
		reach: '.alive',
		isLowBat: 'none',
		id: 'none',
	},
	unifi: {
		Selektor: 'unifi.*.state',
		adapterID: 'unifi',
		adapter: 'Unifi',
		battery: 'none',
		reach: '.state',
		isLowBat: 'none',
		id: 'none',
	},
	wled: {
		Selektor: 'wled.*._online',
		adapterID: 'wled',
		adapter: 'WLED',
		rssiState: '.wifi.rssi',
		battery: 'none',
		reach: '._online',
		isLowBat: 'none',
		id: 'none',
	},
	yeelight: {
		Selektor: 'yeelight-2.*.connect',
		adapterID: 'yeelight',
		adapter: 'Yeelight',
		battery: 'none',
		reach: '.connect',
		isLowBat: 'none',
	},
	zigbee: {
		Selektor: 'zigbee.*.link_quality',
		adapterID: 'zigbee',
		adapter: 'Zigbee',
		battery: '.battery',
		rssiState: '.link_quality',
		reach: '.available',
		isLowBat: '.battery_low',
	},
	zigbee2MQTT: {
		Selektor: 'zigbee2mqtt.*.link_quality',
		adapterID: 'zigbee2MQTT',
		adapter: 'Zigbee2MQTT',
		battery: '.battery',
		rssiState: '.link_quality',
		reach: '.available',
		isLowBat: '.battery_low',
	},
	zwave: {
		Selektor: 'zwave2.*.ready',
		adapterID: 'zwave',
		adapter: 'Z-wave 2',
		battery: '.Battery.level',
		reach: '.ready',
		isLowBat: '.Battery.isLow',
	},
};

module.exports = arrApart;
